apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: imghoard-ingress
spec:
  routes:
    - match: Host(`webhooks.miki.bot`)
      kind: Rule
      services:
        - kind: Service
          name: imghoard
          port: 80